baseURL = 'http://example.org/'
languageCode = 'en-us'
title = 'Andy Luo'
theme = "archie"


[params]
	mode="toggle" # color-mode → light,dark,toggle or auto
	useCDN=false # don't use CDNs for fonts and icons, instead serve them locally.
	mathjax = true # enable MathJax support
	katex = true # enable KaTeX support

[[menu.main]]
name = "About"
url = "/about"
weight = 1

[[menu.main]]
name = "Bookshelf"
url = "/bookshelf"
weight = 2

[[menu.main]]
name = "Posts"
url = "/posts"
weight = 3